version: "3.7"
services:
  app:
    build: "./"
    command: "pipenv run start"
    environment:
      RUN_MODE: development
      DATABASE_USER: root
      DATABASE_PASSWORD: i18n_sample
      DATABASE_HOST: db
      PIPENV_VENV_IN_PROJECT: "true"
    ports:
      - "5000:5000"
    volumes:
      - "./:/app"
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: i18n_sample
    volumes:
      - "db-data:/var/lib/mysql"
      - "./template/mysql/conf.d:/etc/mysql/conf.d"
    ports:
      - "3316:3306"

volumes:
  db-data:
    driver: local
